### ISSUE TITLE
After you install the extension, how do you stop it being used?

### ISSUE THREAD

**Issue by andupotorac** [muerrilla/stable-diffusion-NPW#12]
If I set it to 0 or to 1 it affects the image I had before installing it. I want to know so I can test.

**Comment by muerrilla** [comment]
Setting it to 1 is the same as not having the extension, unless the new A1111 update has broken it (haven't updated yet).

With NPW 1.0:
![tiger-kej-0](https://github.com/muerrilla/stable-diffusion-NPW/assets/48160881/e32ce510-ee64-4b55-a2cd-c9d4357b4586)

With NPW disabled:
![tiger-GFH-0](https://github.com/muerrilla/stable-diffusion-NPW/assets/48160881/ccbf7cdd-0e4b-400d-bf3e-34f7478907fb)

To make sure, you can disable the extension by going to the extensions tab of the webui, and unchecking the box next to sd-webui-0-NPW, then clicking 'apply and restart UI'.

Let me know if I should close this issue.
