### ISSUE TITLE
Error calling after install

### ISSUE THREAD

**Issue by mpole** [muerrilla/stable-diffusion-NPW#2]
after a quick test, no reactions by NPW, after that i saw some error in the console. 
I disabled all other extensions, and restart, but i got the the same errors.

Error calling: ...\extensions\stable-diffusion-NPW\scripts\npw.py/ui
Traceback (most recent call last):
  File "...\stable-diffusion-webui\modules\scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "...\stable-diffusion-webui\extensions\stable-diffusion-NPW\scripts\npw.py", line 39, in ui
    weight_input_slider.release(None, weight_input_slider, weight_input, _js="(x) => x")
AttributeError: 'Slider' object has no attribute 'release'

Error calling: ...\stable-diffusion-webui\extensions\stable-diffusion-NPW\scripts\npw.py/ui
Traceback (most recent call last):
  File "...\stable-diffusion-webui\modules\scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "...\stable-diffusion-webui\extensions\stable-diffusion-NPW\scripts\npw.py", line 39, in ui
    weight_input_slider.release(None, weight_input_slider, weight_input, _js="(x) => x")
AttributeError: 'Slider' object has no attribute 'release'

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 1.5s (list extensions: 1.0s, load scripts: 0.2s, create ui: 0.2s).
Error running process: ...\stable-diffusion-webui\extensions\stable-diffusion-NPW\scripts\npw.py
Traceback (most recent call last):
  File "...\stable-diffusion-webui\modules\scripts.py", line 409, in process
    script.process(p, *script_args)
TypeError: Script.process() missing 1 required positional argument: 'weight'

**Comment by muerrilla** [comment]
You need to update your sd-webui to the latest version, but beware, as it might be a bit buggy.

**Comment by muerrilla** [comment]
@mpole if you decide you don't want to update yet, you can edit npw.py on line 39 and change `release` to `change`. Feedback might become a bit laggy, but should work.

**Comment by mpole** [comment]
> line 39 change `release` to `change`. Feedback might become a bit laggy, but should work.

this work, thx! ... sd-webui updated if i have some more time ;)
