### ISSUE TITLE
[ Feature Idea ] Automatic NPW settings to boost it/s

### ISSUE THREAD

**Issue by Aptronymist** [muerrilla/stable-diffusion-NPW#6]
I was reading about how having your positive/negative prompts closer in size increased image generation speed, and I thought of your extension, and how wonderful it would be to have it automatically (with a checkbox of course) increase or decrease the negative prompt strength to sync up with the positive prompt token value. I understood that having those values the same or close could increase performance by 15% or so, so I figured it's something you might want to consider.

**Comment by muerrilla** [comment]
Didn't know about that. Care to share the reading material?
